# Generated by Django 5.1.7 on 2025-03-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('workshop', models.CharField(max_length=100)),
            ],
        ),
    ]
