# Generated by Django 5.1.7 on 2025-03-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0002_rename_image_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tool_photos/'),
        ),
    ]
