# Generated by Django 5.1.4 on 2025-04-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0004_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
